#!perl

=head1 NAME

  Trees

=cut

use strict;
use warnings;
use Time::Piece;
use Abills::Base qw(time2sec);
use Tree::db::Tree;
use Data::Dumper;

our ($html, %FORM, $db, %conf, $admin, %lang, $index);
my  ($table, $button_add, $button_change);

sub add_type {

  my $Tree = Tree->new($db, $admin, \%conf);
  my $type_list = $Tree->type_list({ COLS_NAME => 1 });
  my $title = $lang{ADD_TYPE};

  if ($FORM{ADD}) {
    $Tree->add_type( {%FORM} );
    $html->message('info', $lang{ADD_MESSEGES}, $lang{SUC_TYPE});
  } elsif ($FORM{del}) {
      $Tree->del_type( {ID => $FORM{del} });
      $html->message('err', $lang{DEL_MESSEGES}, $lang{DEL_TYPE});
  } elsif ($FORM{CHANGE}) {
      $html->message('warn', $lang{EDIT_MESSEGES}, $lang{EDIT_MSG});
      $title = $lang{EDIT_TYPE};
  } elsif ($FORM{CHANGE_BTN}) {
	  $Tree->type_change(\%FORM);
	  $html->message('info', $lang{EDIT_MESSEGES}, $lang{SUC_EDIT_MSG});

  }

  if(!$FORM{CHANGE}){
	  $button_add    = $html->form_input("ADD", $lang{ADD},       {TYPE => "submit"});
  }
  if($FORM{CHANGE}){
	  $button_change = $html->form_input("CHANGE_BTN", $lang{CHANGE}, {TYPE => "submit"});
      
  }

  ($table, $type_list) = result_former({
    INPUT_DATA          => $Tree,
    FUNCTION            => 'type_list',
    LIST                => $type_list,
    BASE_FIELDS         => 2,
    SKIP_USER_TITLE     => 1,
    DEFAULT_FIELDS      => 'id, TYPE',
    EXT_TITLES          => {
      id                => $lang{ID},
      type_of_tree      => $lang{TYPE},
    },
    SKIP_PAGES          => 1,
    TABLE               => {
      width             => '100%',
      caption           => "$lang{TYPES_LIST}",
      qs                => $pages_qs,
      pages             => 500,
      ID                => 'TREES_ID',
    },
    MODULE              => 'Tree',
  });

  $html->tpl_show(_include('main_page_one', 'Tree'), {
      ID            => $FORM{id},
      INDEX         => $index,
      ADD_TREE      => $html->form_input('TYPE_OF_TREE', $FORM{type_of_tree}),
      BUTTON_ADD    => $button_add,
      BUTTON_CHANGE => $button_change,
      TITLE         => $title,
    });

  foreach my $line (@$type_list) {
      my @fields_array = ();

      push @fields_array, $line->{"id"};
      push @fields_array, $line->{"type_of_tree"};

      push @fields_array, ($html->button($lang{CHANGE},
          "index=$index&id=$line->{id}&type_of_tree=$line->{type_of_tree}&CHANGE=1"._translate($line->{position}),
          { class => 'change' } ));
      push @fields_array, ($html->button($lang{DELETE},
          "index=$index&del=$line->{id}"._translate($line->{position}),
          { CONFIRM => $lang{DELETE_CONFIRM} . " " . $line->{type_of_tree} . "?",
			class => 'del' } ));

      $table->addrow(@fields_array);
    }

  print $table->show();

  return 1;
}

sub add_sort {
  my $Tree = Tree->new($db, $admin, \%conf);
  my $type_list        = $Tree->type_list(   { COLS_NAME => 1} );
  my $species_list     = $Tree->species_list({ COLS_NAME => 1} );
  my @files            = ();

  my $title = $lang{ADD_SORT};

  if(!$FORM{CHANGE}){
	  $button_add    = $html->form_input("ADD",    $lang{ADD},    {TYPE => "submit"} );
  }
  if($FORM{CHANGE}){
	  $button_change = $html->form_input("CHANGE_BTN", $lang{CHANGE}, {TYPE => "submit"} );
  }

  if ($FORM{ADD} && $FORM{TYPE_ID} == 0) {
    $html->message('warn', $lang{ERROR}, $lang{ERROR_TYPE});
  } elsif ($FORM{del} ) {
      $Tree->del_species({ID => $FORM{del} });
      $html->message('err', $lang{DEL_MESSEGES}, $lang{DEL_SORT} );
  } elsif ($FORM{CHANGE} ) {
      $html->message('warn', $lang{EDIT_MESSEGES}, $lang{EDIT_MSG} );
      $title = $lang{EDIT_SORT};
  } elsif ($FORM{ADD} ) {
    $Tree->add_species({%FORM} );
    $html->message('info', $lang{ADD_MESSEGES}, $lang{SUC_SORT} );
  } elsif ($FORM{CHANGE_BTN}){
	$Tree->species_change(\%FORM);
    $html->message('info', $lang{EDIT_MESSEGES}, $lang{SUC_EDIT_MSG});
  }

    push @files, "--";
    my @id_files = ();

    foreach my $line (@$type_list) {
        push @id_files, $line->{"id"};
        push @files, $line->{"type_of_tree"};
    }

  ($table, $species_list) = result_former( {
    INPUT_DATA          => $Tree,
    FUNCTION            => 'species_list',
    LIST                => $species_list,
    BASE_FIELDS         => 3,
    SKIP_USER_TITLE     => 1,
    DEFAULT_FIELDS      => 'id, species, type_of_tree',
    EXT_TITLES          => {
      id                => $lang{ID},
      type_of_tree      => $lang{TYPE},
      species           => $lang{SPECIES},
    },
    SKIP_PAGES          => 1,
    TABLE               => {
      width             => '100%',
      caption           => "$lang{SORTS_LIST}",
      qs                => $pages_qs,
      pages             => 500,
      ID                => 'TREES_ID',
    },
    MODULE              => 'Tree',
  });

  $html->tpl_show(_include('main_page_two', 'Tree'), {
    TYPE_TREE        =>  $html->form_select(
      'TYPE_ID',
      {
          SELECTED    => $FORM{TYPE_ID_EDIT},
          SEL_LIST    => translate_list($Tree->type_list({ COLS_NAME => 1 }),
              'type_of_tree'
          ),
          SEL_KEY     => 'id',
          SEL_VALUE   => 'type_of_tree',
          NO_ID       => 1,
          SEL_OPTIONS => { '' => '--' },
      }),
    ID               => $FORM{ID},
    INDEX            => $index,
    BUTTON_ADD       => $button_add,
    BUTTON_CHANGE    => $button_change,
    ADD_TREE_SORT    => $html->form_input('SPECIES', $FORM{SPECIES_EDIT} ),
    TITLE            => $title,
  });


  foreach my $line (@$species_list) {
    my @fields_array = ();
    push @fields_array, $line->{"id"};
    push @fields_array, $line->{"type_of_tree"};
    push @fields_array, $line->{"species"};

    push @fields_array, ($html->button($lang{CHANGE},
        "index=$index&ID=$line->{id}&TYPE_ID_EDIT=$line->{type_id}&SPECIES_EDIT=$line->{species}&CHANGE=1"._translate($line->{position} ),
        { class => 'change' } ));
    push @fields_array, ($html->button($lang{DELETE},
        "index=$index&del=$line->{id}"._translate($line->{position} ),
        { CONFIRM => $lang{DELETE_CONFIRM} . " " . $line->{species} . "?",
		  class => 'del' } ));

    $table->addrow(@fields_array);
  }

  print $table->show();

  return 1;
}

sub search_tree {
  my ($button_search, $button_clear);

    if ($FORM{EDIT}) {
        $html->message('warn', $lang{EDIT_MESSEGES}, $lang{EDIT_SORT});
    }

  my $style            = "box box-theme collapsed-box";
  
  my $Tree          = Tree->new($db, $admin, \%conf);
  if($FORM{DRAW}) {
        # Abills::Base::_bp("", \%FORM);
        $Tree->tree_change({
            ID         => $FORM{ID},
            EXT_ID     => $FORM{EXT_ID},
            SPECIES_ID => $FORM{SORT},
            AGE        => $FORM{AGE},
            STATUS     => $FORM{STATUS_EDIT},
            COMMENT    => $FORM{COMMENTS},
        });
        $style = "box box-theme collapsed-box";
    } elsif ($FORM{EDIT}) {
        $style = "box box-theme";
    }
  my $tree_list;
  if(!$FORM{DRAW}){
  $tree_list     = $Tree->tree_list({
      COLS_NAME  => 1,
      MIN_AGE    => $FORM{MIN_AGE},
      MAX_AGE    => $FORM{MAX_AGE},
      TYPE_ID    => $FORM{TYPE},
      SPECIES_ID => $FORM{SORT},
      STATUS     => $FORM{STATUS},
  });}
  else{
      $tree_list     = $Tree->tree_list({
      COLS_NAME  => 1,
      });
  };

    my $type_list     = $Tree->type_list({COLS_NAME    => 1});
    my $sort_list     = $Tree->species_list({COLS_NAME => 1});
    my @status_tree   = ('Здорове', 'Хворе');
    my $button_edit   = $html->form_input('DRAW', $lang{EDIT}, {TYPE => 'submit'});
    my @status_tree   = ('Здорове', 'Хворе');
    my @type = ();
    my @sort = ();


    # box box-theme collapsed-box
    # box box-theme

    

    $button_search = $html->form_input("SEARCH", $lang{SEARCH}, {TYPE => "submit"} );
    $button_clear  = $html->form_input("CLEAR",  $lang{CLEAR},  {TYPE => "submit"} );

    # $Tree->add_tree({
    #     EXT_ID     => "2",
    #     SPECIES_ID => 43,
    #     AGE        => 92,
    #     COORDX     => 48.5303,
    #     COORDY     => 25.5303,
    #     STATUS     => "Хворе",
    #     COMMENT    => " ",
    # });

    if ($FORM{del}) {
        $Tree->del_tree({ID => $FORM{del}})
    }

    # my $js_locations_arr;
    # foreach my $tree (@$tree_list){
    #     $js_locations_arr.= "[\"" . $tree -> {species} . "\"," . $tree -> {coordx} . "," . $tree -> {coordy} . "," . $tree -> {id} . "],";
    # }
    my $js_locations_arr;
    foreach my $tree (@$tree_list){
        my $name = "<h3>"           . $tree -> {species} . "</h3>" .
            "<b>Номер дерева: </b>" . $tree -> {ext_id}  . "<br>" .
            "<b>Вік: </b>"          . $tree -> {age}     . "<br>" .
            "<b>Статус: </b>"       . $tree -> {status};
        $js_locations_arr.= "[\"" . $name . "\"," . $tree -> {coordx} . "," . $tree -> {coordy} . "," . $tree -> {id} . "],";
    }


  push @type, "--";
  foreach my $line (@$type_list) {
    push @type, $line->{"type_of_tree"};
  }

  push @sort, "--";
  foreach my $line (@$sort_list) {
    push @sort, $line->{"species"};
  }

  $html->tpl_show(_include('main_page_three', 'Tree'), {
    ID            => $FORM{ID},
    INDEX         => $index,
    ONE_NUMB_YEAR => $html->form_input('MIN_AGE',  $FORM{MIN_AGE}),
    TWO_NUMB_YEAR => $html->form_input('MAX_AGE',  $FORM{MAX_AGE}),
    LOCATIONS_ARR => $js_locations_arr,
    STATUS        => $html->form_select(
      'STATUS',
      {
          SELECTED            => $FORM{STATUS},
          SEL_ARRAY           => \@status_tree,
          NO_ID               => 1,
          SEL_OPTIONS => { '' => '--' },
      }),
    TYPE          => $html->form_select(
      'TYPE',
      {
        SELECTED            => $FORM{TYPE},
        SEL_ARRAY           => \@type,
        ARRAY_NUM_ID        => 1,
          
      }),
    SORT             => $html->form_select(
      'SORT',
      {
        SELECTED            => $FORM{SORT},
        SEL_ARRAY           => \@sort,
        ARRAY_NUM_ID        => 1,
      }),
    DATE_CHANGE   => $html->form_input('DATE_CHANGE', $FORM{DATE_CHANGE}),
    BUTTON_SEARCH => $button_search,
    BUTTON_CLEAR  => $button_clear,
  });


    $html->tpl_show(_include('main_page_five', 'Tree'), {
        ID            => $FORM{ID},
        INDEX         => $index,
        TYPE          => $html->form_select(
            'TYPE',
            {
                SELECTED    => $FORM{TYPE},
                SEL_LIST    => translate_list($Tree->type_list({ COLS_NAME => 1 },
                    'type_of_tree')),
                SEL_KEY     => 'id',
                SEL_VALUE   => 'type_of_tree',
                NO_ID       => 1,
                SEL_OPTIONS => { '' => '--' },
            }),
        SORT          => $html->form_select(
            'SORT',
            {
                SELECTED    => $FORM{SORT},
                SEL_LIST    => translate_list($Tree->species_list({ COLS_NAME => 1 },
                    'species')),
                SEL_KEY     => 'id',
                SEL_VALUE   => 'species',
                NO_ID       => 1,
                SEL_OPTIONS => { '' => '--' },
            }),
        ONE_NUMB_YEAR => $html->form_input('AGE', $FORM{AGE}),
        STATUS        => $html->form_select(
            'STATUS_EDIT',
            {
                SELECTED    => $FORM{STATUS_EDIT},
                SEL_ARRAY   => \@status_tree,
                SEL_OPTIONS => { '' => '--' },
                NO_ID       => 1,
            }),
        NUMBER_TREE   => $html->form_input('EXT_ID', $FORM{EXT_ID}),
        BUTTON_EDIT   => $button_edit,
        STYLE_BOX     => $style,
    });
  ($table, $tree_list) = result_former( {
    INPUT_DATA          => $Tree,
    LIST                => $tree_list,
    BASE_FIELDS         => 9,
    SKIP_USER_TITLE     => 1,
    DEFAULT_FIELDS      => 'id, ext_id, species_id, species, age,
                            coordx, coordy, status, comment',
    EXT_TITLES          => {
      id                     => $lang{ID},
      ext_id                 => $lang{EXT_ID},
      species_id             => $lang{SPECIES},
        species              => $lang{TYPE},
      age                    => $lang{AGE},
      coordx                 => $lang{COORDX},
      coordy                 => $lang{COORDY},
      status                 => $lang{STATUS},
      comment                => $lang{COMMENT},
    },
    SKIP_PAGES          => 1,
    TABLE               => {
      width             =>  '100%',
      caption           =>  "$lang{LOGO}",
      qs                =>  $pages_qs,
      pages             =>  500,
      ID                =>  'TREES_ID',
    },
    MODULE              =>  'Tree',
  });

  foreach my $line (@$tree_list) {
        my @fields_array = ();

        push @fields_array, $line->{"id"};
        push @fields_array, $line->{"ext_id"};
        push @fields_array, $line->{"species"};
        push @fields_array, $line->{"age"};
        push @fields_array, $line->{"coordx"};
        push @fields_array, $line->{"coordy"};
        push @fields_array, $line->{"status"};
        push @fields_array, $line->{"comment"};
        push @fields_array, $line->{"type_of_tree"};


      push @fields_array, ($html->button($lang{CHANGE},
          "index=$index&ID=$line->{id}&TYPE_TREE=$line->{type_of_tree}&EXT_ID=$line->{ext_id}&SPECIES=$line->{species}&AGE=$line->{age}&COORDX=$line->{coordx}&COORDY=$line->{coordy}&STATUS_EDIT=$line->{status}&COMMENT=$line->{comment}&EDIT=1"._translate($line->{position} ),
          { class => 'change' } ));
        push @fields_array, ($html->button($lang{DELETE},
          "index=$index&del=$line->{id}"._translate($line->{position} ),
          { class => 'del' } ));

        $table->addrow(@fields_array);
  }

  print $table->show();

    return 1;
}

sub add_trees {
    my $Tree = Tree->new($db, $admin, \%conf);
    my $type_list = $Tree->type_list({ COLS_NAME => 1 });
    my $species = $Tree->species_list({ COLS_NAME => 1 });
    my @files_type = ();
    my @files_species = ();
    my $place = 'Home';
    my $cord_x = 48.537917;
    my $cord_y = 25.024278;
    my $location_id = 1;

    if ($FORM{ADD}) {
        $Tree->add_tree({
            EXT_ID     => $FORM{TREE_ID},
            SPECIES_ID => $FORM{SPECIES_ID},
            AGE        => $FORM{AGE},
            COORDX     => $FORM{COORD_X},
            COORDY     => $FORM{COORD_Y},
            STATUS     => $FORM{STATUS},
            COMMENT    => $FORM{COMMENTS},
        });
        $html->message('info', $lang{ADD_MESSEGES}, $lang{SUC_TYPE});
    }
    elsif ($FORM{del}) {
        $Tree->del_species({ ID => $FORM{del} });
        $html->message('err', $lang{DEL_MESSEGES}, $lang{DEL_TYPE});
    }
    elsif ($FORM{CHANGE}) {
        $Tree->species_change(\%FORM);
        $html->message('warn', $lang{EDIT_MESSEGES}, $lang{EDIT_MESSEGES});
    }

    $button_add = $html->form_input("ADD", $lang{ADD}, { TYPE => "submit" });
    $button_change = $html->form_input("CHANGE", $lang{CHANGE}, { TYPE => "submit" });

    push @files_type, "--";
    foreach my $line (@$type_list) {
        push @files_type, $line->{"type_of_tree"};
    }
    push @files_species, "--";
    foreach my $line (@$species) {
        push @files_species, $line->{"species"};
    }

    # print $coord_x." ".$coord_y;

    $html->tpl_show(_include('main_page_four', 'Tree'), {
        TYPE_TREE     => $html->form_select(
            'TYPE_ID',
            {
                SELECTED     => $FORM{TYPE_ID},
                SEL_ARRAY    => \@files_type,
                ARRAY_NUM_ID => 1,
            }),
        ID            => $FORM{ID},
        INDEX         => $index,
        BUTTON_ADD    => $button_add,
        BUTTON_CHANGE => $button_change,
        ADD_TREE_SORT => $html->form_select(
            'SPECIES_ID',
            {
                SELECTED     => $FORM{SPECIES_ID},
                SEL_ARRAY    => \@files_species,
                ARRAY_NUM_ID => 1,
            }),
        AGE           => $html->form_input('AGE', $FORM{age}),
        STATUS        => $html->form_input('STATUS', $FORM{status}),
        TREE_ID       => $html->form_input('TREE_ID', $FORM{tree_id}),
        CORD_X        => $html->form_input('CORD_X', $FORM{cord_x}),
        CORD_Y        => $html->form_input('CORD_Y', $FORM{cord_y}),
        PLACE         => $place,
        COORD_X       => $cord_x,
        COORD_Y       => $cord_y,
        LOCATION_ID   => $location_id
    });
    return 1;
}

1;
